/*
    Copyright (C) 2005 Development Team of Peragro Tempus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//  !! This file was automatically generated by a network code generator   !!
//  !! Do not change this file since all changes will be overwritten later !!
//  !! Instead please change the source files here: peragro/data/generate  !!

#ifndef ENVIRONMENTMESSAGES_H
#define ENVIRONMENTMESSAGES_H

#include "netmessage.h"

namespace ENVIRONMENT
{
  enum MESSAGES
  {
    INITTIME=0,
    UPDATETIME=1,
    WEATHER=2
  };
}

class InitTimeMessage : public NetMessage
{
  unsigned char minute;
  unsigned char hour;
  unsigned char minutesperhour;
  unsigned char hoursperday;
  unsigned int realpergame;

public:
  InitTimeMessage() : NetMessage(MESSAGES::ENVIRONMENT,ENVIRONMENT::INITTIME)
  {
  }

  ~InitTimeMessage()
  {
  }

  bool serialise(ByteStream* bs);
  void deserialise(ByteStream* bs);

  unsigned char getMinute() const { return minute; }
  void setMinute(unsigned char x) { minute = x; }

  unsigned char getHour() const { return hour; }
  void setHour(unsigned char x) { hour = x; }

  unsigned char getMinutesPerHour() const { return minutesperhour; }
  void setMinutesPerHour(unsigned char x) { minutesperhour = x; }

  unsigned char getHoursPerDay() const { return hoursperday; }
  void setHoursPerDay(unsigned char x) { hoursperday = x; }

  unsigned int getRealPerGame() const { return realpergame; }
  void setRealPerGame(unsigned int x) { realpergame = x; }

};

class UpdateTimeMessage : public NetMessage
{
  unsigned char minute;
  unsigned char hour;

public:
  UpdateTimeMessage() : NetMessage(MESSAGES::ENVIRONMENT,ENVIRONMENT::UPDATETIME)
  {
  }

  ~UpdateTimeMessage()
  {
  }

  bool serialise(ByteStream* bs);
  void deserialise(ByteStream* bs);

  unsigned char getMinute() const { return minute; }
  void setMinute(unsigned char x) { minute = x; }

  unsigned char getHour() const { return hour; }
  void setHour(unsigned char x) { hour = x; }

};

class WeatherMessage : public NetMessage
{
  unsigned char weatherid;

public:
  WeatherMessage() : NetMessage(MESSAGES::ENVIRONMENT,ENVIRONMENT::WEATHER)
  {
  }

  ~WeatherMessage()
  {
  }

  bool serialise(ByteStream* bs);
  void deserialise(ByteStream* bs);

  unsigned char getWeatherId() const { return weatherid; }
  void setWeatherId(unsigned char x) { weatherid = x; }

};

#endif // ENVIRONMENTMESSAGES_H
