/*
    Copyright (C) 2008 Development Team of Peragro Tempus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//  !! This file was automatically generated by a network code generator   !!
//  !! Do not change this file since all changes will be overwritten later !!
//  !! Instead please change the source files here: peragro/data/generate  !!

#include "common/network/environmentmessages.h"
#include "deserialiser.h"
#include "serialiser.h"

bool InitTimeMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt32(seconds);
  serial.setInt16(epoch);
  serial.setInt8(secondsperminute);
  serial.setInt8(minutesperhour);
  serial.setInt8(hoursperday);
  serial.setInt8(daysperweek);
  serial.setInt8(weekspermonth);
  serial.setInt8(monthsperseason);
  serial.setInt8(seasonsperyear);
  serial.setInt32(gameperreal);
  return serial.isValid();
}

void InitTimeMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  seconds = (unsigned int) serial.getInt32();
  epoch = (unsigned short) serial.getInt16();
  secondsperminute = (unsigned char) serial.getInt8();
  minutesperhour = (unsigned char) serial.getInt8();
  hoursperday = (unsigned char) serial.getInt8();
  daysperweek = (unsigned char) serial.getInt8();
  weekspermonth = (unsigned char) serial.getInt8();
  monthsperseason = (unsigned char) serial.getInt8();
  seasonsperyear = (unsigned char) serial.getInt8();
  gameperreal = (unsigned int) serial.getInt32();
}

bool UpdateTimeMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt32(seconds);
  return serial.isValid();
}

void UpdateTimeMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  seconds = (unsigned int) serial.getInt32();
}

bool WeatherMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt8(weatherid);
  return serial.isValid();
}

void WeatherMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  weatherid = (unsigned char) serial.getInt8();
}

