/*
    Copyright (C) 2008 Development Team of Peragro Tempus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//  !! This file was automatically generated by a network code generator   !!
//  !! Do not change this file since all changes will be overwritten later !!
//  !! Instead please change the source files here: peragro/data/generate  !!

#ifndef NWTYPES_H
#define NWTYPES_H

<<<<<<< HEAD:src/common/network/nwtypes.h
#define MSG_NET_VERSION 2265958605

#define MSG_CLIENT_PEER_VERSION 3326008920
#define MSG_SERVER_PEER_VERSION 260141879
#define MSG_AUTH_PEER_VERSION 1764255664
=======
#define MSG_NET_VERSION 3463756142

#define MSG_CLIENT_PEER_VERSION 3538941946
#define MSG_SERVER_PEER_VERSION 1958947966
>>>>>>> Added death combat message. Added a notification distance variable to interaction manager to control who will get notified by local happenings. Re-factories some code into functions in interaction manager. Added doxygen comments.:src/common/network/nwtypes.h

#define MSG_HANDLER_COUNT 14

namespace MESSAGES
{
  enum HANDLERS
  {
    CONNECTION=0,
    USER=1,
    ENTITY=2,
    CHAT=3,
    SKILL=4,
    DOOR=5,
    QUEST=6,
    TRADE=7,
    ENVIRONMENT=8,
    BOOK=9,
    ADMIN=10,
    PLAYER=11,
    COMBAT=12,
    AUTH=13
  };
}

#endif // NWTYPES_H
