/*
    Copyright (C) 2008 Development Team of Peragro Tempus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//  !! This file was automatically generated by a network code generator   !!
//  !! Do not change this file since all changes will be overwritten later !!
//  !! Instead please change the source files here: peragro/data/generate  !!

#include "common/network/usermessages.h"
#include "deserialiser.h"
#include "serialiser.h"

bool LoginRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setString(username);
  serial.setString(password);
  return serial.isValid();
}

void LoginRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  username = serial.getString();
  serial.getString(password);
}

bool LoginResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setString(error);
  serial.setInt8(isadmin?1:0);
  return serial.isValid();
}

void LoginResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  error = serial.getString();
  isadmin = serial.getInt8() != 0;
}

bool RegisterRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setString(username);
  serial.setString(password);
  return serial.isValid();
}

void RegisterRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  username = serial.getString();
  serial.getString(password);
}

bool RegisterResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setString(error);
  return serial.isValid();
}

void RegisterResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  error = serial.getString();
}

bool CharListMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt24(charactercount);
  for ( size_t i = 0; i < charactercount ; i++ )
  {
    serial.setInt32(character[i].charid);
    serial.setString(character[i].name);
    serial.setInt8(character[i].haircolour[0]);
    serial.setInt8(character[i].haircolour[1]);
    serial.setInt8(character[i].haircolour[2]);
    serial.setInt8(character[i].skincolour[0]);
    serial.setInt8(character[i].skincolour[1]);
    serial.setInt8(character[i].skincolour[2]);
    serial.setInt8(character[i].decalcolour[0]);
    serial.setInt8(character[i].decalcolour[1]);
    serial.setInt8(character[i].decalcolour[2]);
  };

  return serial.isValid();
}

void CharListMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  charactercount = (unsigned int) serial.getInt24();
  setCharacterCount(charactercount);
  for ( size_t i = 0; i < charactercount ; i++ )
  {
    character[i].charid = (unsigned int) serial.getInt32();
    character[i].name = serial.getString();
    character[i].haircolour[0] = (unsigned char) serial.getInt8();
    character[i].haircolour[1] = (unsigned char) serial.getInt8();
    character[i].haircolour[2] = (unsigned char) serial.getInt8();
    character[i].skincolour[0] = (unsigned char) serial.getInt8();
    character[i].skincolour[1] = (unsigned char) serial.getInt8();
    character[i].skincolour[2] = (unsigned char) serial.getInt8();
    character[i].decalcolour[0] = (unsigned char) serial.getInt8();
    character[i].decalcolour[1] = (unsigned char) serial.getInt8();
    character[i].decalcolour[2] = (unsigned char) serial.getInt8();
  };

}

bool CharCreateRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setString(name);
  serial.setString(racename);
  serial.setInt8(haircolour[0]);
  serial.setInt8(haircolour[1]);
  serial.setInt8(haircolour[2]);
  serial.setInt8(skincolour[0]);
  serial.setInt8(skincolour[1]);
  serial.setInt8(skincolour[2]);
  serial.setInt8(decalcolour[0]);
  serial.setInt8(decalcolour[1]);
  serial.setInt8(decalcolour[2]);
  return serial.isValid();
}

void CharCreateRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  name = serial.getString();
  racename = serial.getString();
  haircolour[0] = (unsigned char) serial.getInt8();
  haircolour[1] = (unsigned char) serial.getInt8();
  haircolour[2] = (unsigned char) serial.getInt8();
  skincolour[0] = (unsigned char) serial.getInt8();
  skincolour[1] = (unsigned char) serial.getInt8();
  skincolour[2] = (unsigned char) serial.getInt8();
  decalcolour[0] = (unsigned char) serial.getInt8();
  decalcolour[1] = (unsigned char) serial.getInt8();
  decalcolour[2] = (unsigned char) serial.getInt8();
}

bool CharCreateResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt32(charid);
  serial.setString(name);
  serial.setInt8(haircolour[0]);
  serial.setInt8(haircolour[1]);
  serial.setInt8(haircolour[2]);
  serial.setInt8(skincolour[0]);
  serial.setInt8(skincolour[1]);
  serial.setInt8(skincolour[2]);
  serial.setInt8(decalcolour[0]);
  serial.setInt8(decalcolour[1]);
  serial.setInt8(decalcolour[2]);
  serial.setString(error);
  return serial.isValid();
}

void CharCreateResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  charid = (unsigned int) serial.getInt32();
  name = serial.getString();
  haircolour[0] = (unsigned char) serial.getInt8();
  haircolour[1] = (unsigned char) serial.getInt8();
  haircolour[2] = (unsigned char) serial.getInt8();
  skincolour[0] = (unsigned char) serial.getInt8();
  skincolour[1] = (unsigned char) serial.getInt8();
  skincolour[2] = (unsigned char) serial.getInt8();
  decalcolour[0] = (unsigned char) serial.getInt8();
  decalcolour[1] = (unsigned char) serial.getInt8();
  decalcolour[2] = (unsigned char) serial.getInt8();
  error = serial.getString();
}

bool CharSelectRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt32(charid);
  return serial.isValid();
}

void CharSelectRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  charid = (unsigned int) serial.getInt32();
}

bool CharSelectResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt32(entityid);
  serial.setString(error);
  return serial.isValid();
}

void CharSelectResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  entityid = (unsigned int) serial.getInt32();
  error = serial.getString();
}

bool MeshListRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  return serial.isValid();
}

void MeshListRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
}

bool MeshListResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt24(meshescount);
  for ( size_t i = 0; i < meshescount ; i++ )
  {
    serial.setInt32(meshes[i].meshid);
    serial.setString(meshes[i].meshname);
    serial.setString(meshes[i].filename);
  };

  return serial.isValid();
}

void MeshListResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  meshescount = (unsigned int) serial.getInt24();
  setMeshesCount(meshescount);
  for ( size_t i = 0; i < meshescount ; i++ )
  {
    meshes[i].meshid = (unsigned int) serial.getInt32();
    meshes[i].meshname = serial.getString();
    meshes[i].filename = serial.getString();
  };

}

bool RaceListRequestMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  return serial.isValid();
}

void RaceListRequestMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
}

bool RaceListResponseMessage::serialise(ByteStream* bs)
{
  Serialiser serial(bs);
  serial.setInt8(type);
  serial.setInt8(id);
  serial.setInt24(racescount);
  for ( size_t i = 0; i < racescount ; i++ )
  {
    serial.setInt32(races[i].raceid);
    serial.setString(races[i].racename);
    serial.setInt32(races[i].meshid);
  };

  return serial.isValid();
}

void RaceListResponseMessage::deserialise(ByteStream* bs)
{
  Deserialiser serial(bs);
  type = serial.getInt8();
  id = serial.getInt8();
  racescount = (unsigned int) serial.getInt24();
  setRacesCount(racescount);
  for ( size_t i = 0; i < racescount ; i++ )
  {
    races[i].raceid = (unsigned int) serial.getInt32();
    races[i].racename = serial.getString();
    races[i].meshid = (unsigned int) serial.getInt32();
  };

}

