/*
    Copyright (C) 2008 Development Team of Peragro Tempus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//  !! This file was automatically generated by a network code generator   !!
//  !! Do not change this file since all changes will be overwritten later !!
//  !! Instead please change the source files here: peragro/data/generate  !!

#include "client/network/resourcehandler.h"

#include "common/event/eventmanager.h"
#include "common/event/entityevent.h"

#include "client/pointer/pointer.h"

void ResourceHandler::handleResourceList(GenericMessage* msg)
{
  ResourceListMessage pmsg;
  pmsg.deserialise(msg->getByteStream());

  using namespace PT::Events;
  EventManager* evmgr = PointerLibrary::getInstance()->getEventManager();
  {
    csRef<iEvent> pEvent = evmgr->CreateEvent(EntityHelper::MakeEntitySpecific("entity.resource.list", pmsg.getEntityId()), true);
    pEvent->Add("entityId", pmsg.getEntityId());
    csRef<iEvent> resourcesList = evmgr->CreateEvent("resourcesList", true);
    for (unsigned char i = 0; i < pmsg.getResourcesCount(); i++)
    {
      std::stringstream itemName;
      itemName << "resources" << "_" << i;
      csRef<iEvent> item = evmgr->CreateEvent(itemName.str().c_str(), true);
      item->Add("resourceId", pmsg.getResourceId(i));
      item->Add("name", *pmsg.getName(i)?*pmsg.getName(i):"");
      item->Add("value", pmsg.getValue(i));
      item->Add("maxValue", pmsg.getMaxValue(i));
      resourcesList->Add(itemName.str().c_str(), item);
    }
    pEvent->Add("resourcesList", resourcesList);

    evmgr->AddEvent(pEvent);
  }

} // end handleResourceList

void ResourceHandler::handleResourceUpdate(GenericMessage* msg)
{
  ResourceUpdateMessage pmsg;
  pmsg.deserialise(msg->getByteStream());

  using namespace PT::Events;
  EventManager* evmgr = PointerLibrary::getInstance()->getEventManager();
  {
    csRef<iEvent> pEvent = evmgr->CreateEvent(EntityHelper::MakeEntitySpecific("entity.resource.update", pmsg.getEntityId()), true);
    pEvent->Add("entityId", pmsg.getEntityId());
    pEvent->Add("resourceId", pmsg.getResourceId());
    pEvent->Add("value", pmsg.getValue());
    pEvent->Add("maxValue", pmsg.getMaxValue());

    evmgr->AddEvent(pEvent);
  }

} // end handleResourceUpdate

