// This file is automatically generated.
#include "cssysdef.h"

struct CS_IMPORT_SYM _Bind_peragro_static_plugins
{
  _Bind_peragro_static_plugins ();
};
namespace { _Bind_peragro_static_plugins bind_peragro_static_plugins; }
// This file is automatically generated.

