// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cmdmanager[] =
"<?xml version=\"1.0\"?>"
"<!-- cmdmanager.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.commands.manager</name>"
"        <implementation>CommandManager</implementation>"
"        <description>Command Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CommandManager_FACTORY_REGISTER_DEFINED 
  #define CommandManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CommandManager) 
  #endif

class cmdmanager
{
SCF_REGISTER_STATIC_LIBRARY(cmdmanager,metainfo_cmdmanager)
  #ifndef CommandManager_FACTORY_REGISTERED 
  #define CommandManager_FACTORY_REGISTERED 
    CommandManager_StaticInit CommandManager_static_init__; 
  #endif
public:
 cmdmanager();
};
cmdmanager::cmdmanager() {}

}
