// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_componentstats[] =
"<?xml version=\"1.0\"?>"
"<!-- Stats.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.entity.stats</name>"
"        <implementation>ComponentFStats</implementation>"
"        <description>Perago player entity stats</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ComponentFStats_FACTORY_REGISTER_DEFINED 
  #define ComponentFStats_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ComponentFStats) 
  #endif

class componentstats
{
SCF_REGISTER_STATIC_LIBRARY(componentstats,metainfo_componentstats)
  #ifndef ComponentFStats_FACTORY_REGISTERED 
  #define ComponentFStats_FACTORY_REGISTERED 
    ComponentFStats_StaticInit ComponentFStats_static_init__; 
  #endif
public:
 componentstats();
};
componentstats::componentstats() {}

}
