// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cmdhelp[] =
"<?xml version=\"1.0\"?>"
"<!-- cmdhelp.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.commands.help</name>"
"        <implementation>cmdHelp</implementation>"
"        <description>Help Command</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef cmdHelp_FACTORY_REGISTER_DEFINED 
  #define cmdHelp_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(cmdHelp) 
  #endif

class cmdhelp
{
SCF_REGISTER_STATIC_LIBRARY(cmdhelp,metainfo_cmdhelp)
  #ifndef cmdHelp_FACTORY_REGISTERED 
  #define cmdHelp_FACTORY_REGISTERED 
    cmdHelp_StaticInit cmdHelp_static_init__; 
  #endif
public:
 cmdhelp();
};
cmdhelp::cmdhelp() {}

}
