// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_component_playercontrols[] =
"<?xml version=\"1.0\"?>"
"<!-- NetworkMove.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.entity.input.playercontrols</name>"
"        <implementation>ComponentFPlayerControls</implementation>"
"        <description>Perago player entity movement controls</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ComponentFPlayerControls_FACTORY_REGISTER_DEFINED 
  #define ComponentFPlayerControls_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ComponentFPlayerControls) 
  #endif

class component_playercontrols
{
SCF_REGISTER_STATIC_LIBRARY(component_playercontrols,metainfo_component_playercontrols)
  #ifndef ComponentFPlayerControls_FACTORY_REGISTERED 
  #define ComponentFPlayerControls_FACTORY_REGISTERED 
    ComponentFPlayerControls_StaticInit ComponentFPlayerControls_static_init__; 
  #endif
public:
 component_playercontrols();
};
component_playercontrols::component_playercontrols() {}

}
