// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cmddbg[] =
"<?xml version=\"1.0\"?>"
"<!-- cmddbg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.commands.debug</name>"
"        <implementation>cmdDbg</implementation>"
"        <description>debug commands</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef cmdDbg_FACTORY_REGISTER_DEFINED 
  #define cmdDbg_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(cmdDbg) 
  #endif

class cmddbg
{
SCF_REGISTER_STATIC_LIBRARY(cmddbg,metainfo_cmddbg)
  #ifndef cmdDbg_FACTORY_REGISTERED 
  #define cmdDbg_FACTORY_REGISTERED 
    cmdDbg_StaticInit cmdDbg_static_init__; 
  #endif
public:
 cmddbg();
};
cmddbg::cmddbg() {}

}
