// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cachemanager[] =
"<?xml version=\"1.0\"?>"
"<!-- world.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.cachemanager</name>"
"        <implementation>CacheManager</implementation>"
"        <description>CacheManager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CacheManager_FACTORY_REGISTER_DEFINED 
  #define CacheManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CacheManager) 
  #endif

class cachemanager
{
SCF_REGISTER_STATIC_LIBRARY(cachemanager,metainfo_cachemanager)
  #ifndef CacheManager_FACTORY_REGISTERED 
  #define CacheManager_FACTORY_REGISTERED 
    CacheManager_StaticInit CacheManager_static_init__; 
  #endif
public:
 cachemanager();
};
cachemanager::cachemanager() {}

}
