// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_effectsmanager[] =
"<?xml version=\"1.0\"?>"
"<!-- effectsmanager.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.effectsmanager</name>"
"        <implementation>EffectsManager</implementation>"
"        <description>EffectsManager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef EffectsManager_FACTORY_REGISTER_DEFINED 
  #define EffectsManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(EffectsManager) 
  #endif

class effectsmanager
{
SCF_REGISTER_STATIC_LIBRARY(effectsmanager,metainfo_effectsmanager)
  #ifndef EffectsManager_FACTORY_REGISTERED 
  #define EffectsManager_FACTORY_REGISTERED 
    EffectsManager_StaticInit EffectsManager_static_init__; 
  #endif
public:
 effectsmanager();
};
effectsmanager::effectsmanager() {}

}
