// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_mybody[] =
"<?xml version=\"1.0\"?>"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>recon69.mybodyfactory</name>"
"        <implementation>MyBodyFactory</implementation>"
"        <description>Recon69s body factory</description>"
"      </class>     "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef MyBodyFactory_FACTORY_REGISTER_DEFINED 
  #define MyBodyFactory_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(MyBodyFactory) 
  #endif

class mybody
{
SCF_REGISTER_STATIC_LIBRARY(mybody,metainfo_mybody)
  #ifndef MyBodyFactory_FACTORY_REGISTERED 
  #define MyBodyFactory_FACTORY_REGISTERED 
    MyBodyFactory_StaticInit MyBodyFactory_static_init__; 
  #endif
public:
 mybody();
};
mybody::mybody() {}

}
