// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_worldloader[] =
"<?xml version=\"1.0\"?>"
"<!-- world.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>peragro.world</name>"
"        <implementation>WorldManager</implementation>"
"        <description>World</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef WorldManager_FACTORY_REGISTER_DEFINED 
  #define WorldManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(WorldManager) 
  #endif

class worldloader
{
SCF_REGISTER_STATIC_LIBRARY(worldloader,metainfo_worldloader)
  #ifndef WorldManager_FACTORY_REGISTERED 
  #define WorldManager_FACTORY_REGISTERED 
    WorldManager_StaticInit WorldManager_static_init__; 
  #endif
public:
 worldloader();
};
worldloader::worldloader() {}

}
